import re

GRAPH_APP_SCOPE = ["https://graph.microsoft.com/.default"]
DEFAULT_DELEGATED_SCOPES = ["Mail.ReadWrite"]
DEFAULT_TRIGGER_CATEGORY = "AI Summarize"
DEFAULT_PROCESSED_CATEGORY = "AI Summarized"
DEFAULT_MARKDOWN_FOLDER = "AI Email Summaries"
DEFAULT_SECRETS_FILE = "secrets.env"
DEFAULT_TOKEN_CACHE_FILE = ".ms_token_cache.json"
OPENAI_DEFAULT_MODEL = "gpt-4o-mini"
SUBJECT_PREFIX_PATTERN = re.compile(r"^\s*(re|fw|fwd|aw|wg):\s*", re.IGNORECASE)
SUBJECT_BRACKET_PREFIX = re.compile(r"^\s*\[[^\]]*\]\s*")
INTERNAL_EMAIL_DOMAINS_ENV = "INTERNAL_EMAIL_DOMAINS"
PROJECT_NAMES_ENV = "PROJECT_NAMES"
MS_AUTH_MODE_ENV = "MS_AUTH_MODE"
MS_CLIENT_SECRET_ENV = "MS_CLIENT_SECRET"
MS_DELEGATED_SCOPES_ENV = "MS_DELEGATED_SCOPES"
MS_TOKEN_CACHE_FILE_ENV = "MS_TOKEN_CACHE_FILE"
